empdb:
  image: wlmpoc/mysqlcentos:latest
web:
  build: ./
  command: python manage.py runserver 0.0.0.0:8080
  volumes:
   - .:/home/wlmpoc/DjWebJessie
  ports:
    - "8080:8080"
  links:
    - employeedb
